spring:
  application:
    name: spring-cloud-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8882
server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

#2.10之后要下面
management:
  metrics:
    web:
      server:
        auto-time-requests: false